/* Generated By:JavaCC: Do not edit this line. Python.java */
package javacc;
import java.util.ArrayList;

public class Python implements PythonConstants {

 public String ex;
public static ArrayList<String> tabletokens = new ArrayList();
        void error(String e){
            ex = e;
            System.out.println(ex);
        }

  final public void Start() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE:
      case TRUE:
      case NONE:
      case AND:
      case AS:
      case ASSERT:
      case BREAK:
      case CLASS:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case EXCEPT:
      case FINALLY:
      case FOR:
      case FROM:
      case GLOBAL:
      case IF:
      case IMPORT:
      case IN:
      case IS:
      case LAMBDA:
      case NONLOCAL:
      case NOT:
      case OR:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case WITH:
      case YIELD:
      case RANGE:
      case INPUT:
      case PRINT:
      case VERROR:
      case START:
      case END:
      case SUMA:
      case RESTA:
      case MULTI:
      case POTENCIA:
      case DIVISION:
      case DIVENTERA:
      case MODULO:
      case RECIZQUIERDA:
      case RECDERECHA:
      case AMPERSON:
      case PIPE:
      case CONJUNTO:
      case OPNOT:
      case MENORQUE:
      case MAYORQUE:
      case MENORIGUAL:
      case MAYORIGUAL:
      case IGUALIGUAL:
      case NOTNEG:
      case PARENI:
      case PAREND:
      case PUNTO:
      case CORCHI:
      case CORCHD:
      case LLAVEI:
      case LLAVED:
      case COMA:
      case DOSPUNTOS:
      case PUNTOCOMA:
      case IGUAL:
      case FLECHITA:
      case MASIGUAL:
      case MENOSIGUAL:
      case DIVIGUAL:
      case MULTIGUAL:
      case DDIGUAL:
      case RESIGUAL:
      case ARROBAIGUAL:
      case AMPIGUAL:
      case ORIGUAL:
      case EXIGUAL:
      case MDMDIGUAL:
      case MIMIIGUAL:
      case ASASIGUAL:
      case PESOS:
      case SIGNOINT:
      case ACENTOINV:
      case ENTERO:
      case FLOTANTE:
      case CADENA:
      case CARACTER:
      case BOLEANO:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMILLAS:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE:
        jj_consume_token(FALSE);
        break;
      case TRUE:
        jj_consume_token(TRUE);
        break;
      case NONE:
        jj_consume_token(NONE);
        break;
      case AND:
        jj_consume_token(AND);
        break;
      case AS:
        jj_consume_token(AS);
        break;
      case ASSERT:
        jj_consume_token(ASSERT);
        break;
      case BREAK:
        jj_consume_token(BREAK);
        break;
      case CLASS:
        jj_consume_token(CLASS);
        break;
      case CONTINUE:
        jj_consume_token(CONTINUE);
        break;
      case DEF:
        jj_consume_token(DEF);
        break;
      case DEL:
        jj_consume_token(DEL);
        break;
      case ELIF:
        jj_consume_token(ELIF);
        break;
      case ELSE:
        jj_consume_token(ELSE);
        break;
      case EXCEPT:
        jj_consume_token(EXCEPT);
        break;
      case FINALLY:
        jj_consume_token(FINALLY);
        break;
      case FOR:
        jj_consume_token(FOR);
        break;
      case FROM:
        jj_consume_token(FROM);
        break;
      case GLOBAL:
        jj_consume_token(GLOBAL);
        break;
      case IF:
        jj_consume_token(IF);
        break;
      case IMPORT:
        jj_consume_token(IMPORT);
        break;
      case IN:
        jj_consume_token(IN);
        break;
      case IS:
        jj_consume_token(IS);
        break;
      case LAMBDA:
        jj_consume_token(LAMBDA);
        break;
      case NONLOCAL:
        jj_consume_token(NONLOCAL);
        break;
      case NOT:
        jj_consume_token(NOT);
        break;
      case OR:
        jj_consume_token(OR);
        break;
      case PASS:
        jj_consume_token(PASS);
        break;
      case RAISE:
        jj_consume_token(RAISE);
        break;
      case RETURN:
        jj_consume_token(RETURN);
        break;
      case TRY:
        jj_consume_token(TRY);
        break;
      case WHILE:
        jj_consume_token(WHILE);
        break;
      case WITH:
        jj_consume_token(WITH);
        break;
      case YIELD:
        jj_consume_token(YIELD);
        break;
      case RANGE:
        jj_consume_token(RANGE);
        break;
      case INPUT:
        jj_consume_token(INPUT);
        break;
      case PRINT:
        jj_consume_token(PRINT);
        break;
      case VERROR:
        jj_consume_token(VERROR);
        break;
      case START:
        jj_consume_token(START);
        break;
      case END:
        jj_consume_token(END);
        break;
      case SUMA:
        jj_consume_token(SUMA);
        break;
      case RESTA:
        jj_consume_token(RESTA);
        break;
      case MULTI:
        jj_consume_token(MULTI);
        break;
      case POTENCIA:
        jj_consume_token(POTENCIA);
        break;
      case DIVISION:
        jj_consume_token(DIVISION);
        break;
      case DIVENTERA:
        jj_consume_token(DIVENTERA);
        break;
      case MODULO:
        jj_consume_token(MODULO);
        break;
      case RECIZQUIERDA:
        jj_consume_token(RECIZQUIERDA);
        break;
      case RECDERECHA:
        jj_consume_token(RECDERECHA);
        break;
      case AMPERSON:
        jj_consume_token(AMPERSON);
        break;
      case PIPE:
        jj_consume_token(PIPE);
        break;
      case CONJUNTO:
        jj_consume_token(CONJUNTO);
        break;
      case OPNOT:
        jj_consume_token(OPNOT);
        break;
      case MENORQUE:
        jj_consume_token(MENORQUE);
        break;
      case MAYORQUE:
        jj_consume_token(MAYORQUE);
        break;
      case MENORIGUAL:
        jj_consume_token(MENORIGUAL);
        break;
      case MAYORIGUAL:
        jj_consume_token(MAYORIGUAL);
        break;
      case IGUALIGUAL:
        jj_consume_token(IGUALIGUAL);
        break;
      case NOTNEG:
        jj_consume_token(NOTNEG);
        break;
      case PARENI:
        jj_consume_token(PARENI);
        break;
      case PAREND:
        jj_consume_token(PAREND);
        break;
      case PUNTO:
        jj_consume_token(PUNTO);
        break;
      case CORCHI:
        jj_consume_token(CORCHI);
        break;
      case CORCHD:
        jj_consume_token(CORCHD);
        break;
      case LLAVEI:
        jj_consume_token(LLAVEI);
        break;
      case LLAVED:
        jj_consume_token(LLAVED);
        break;
      case COMA:
        jj_consume_token(COMA);
        break;
      case DOSPUNTOS:
        jj_consume_token(DOSPUNTOS);
        break;
      case PUNTOCOMA:
        jj_consume_token(PUNTOCOMA);
        break;
      case IGUAL:
        jj_consume_token(IGUAL);
        break;
      case FLECHITA:
        jj_consume_token(FLECHITA);
        break;
      case MASIGUAL:
        jj_consume_token(MASIGUAL);
        break;
      case MENOSIGUAL:
        jj_consume_token(MENOSIGUAL);
        break;
      case DIVIGUAL:
        jj_consume_token(DIVIGUAL);
        break;
      case MULTIGUAL:
        jj_consume_token(MULTIGUAL);
        break;
      case DDIGUAL:
        jj_consume_token(DDIGUAL);
        break;
      case RESIGUAL:
        jj_consume_token(RESIGUAL);
        break;
      case ARROBAIGUAL:
        jj_consume_token(ARROBAIGUAL);
        break;
      case AMPIGUAL:
        jj_consume_token(AMPIGUAL);
        break;
      case ORIGUAL:
        jj_consume_token(ORIGUAL);
        break;
      case EXIGUAL:
        jj_consume_token(EXIGUAL);
        break;
      case MDMDIGUAL:
        jj_consume_token(MDMDIGUAL);
        break;
      case MIMIIGUAL:
        jj_consume_token(MIMIIGUAL);
        break;
      case ASASIGUAL:
        jj_consume_token(ASASIGUAL);
        break;
      case PESOS:
        jj_consume_token(PESOS);
        break;
      case SIGNOINT:
        jj_consume_token(SIGNOINT);
        break;
      case ACENTOINV:
        jj_consume_token(ACENTOINV);
        break;
      case ENTERO:
        jj_consume_token(ENTERO);
        break;
      case FLOTANTE:
        jj_consume_token(FLOTANTE);
        break;
      case CADENA:
        jj_consume_token(CADENA);
        break;
      case CARACTER:
        jj_consume_token(CARACTER);
        break;
      case BOLEANO:
        jj_consume_token(BOLEANO);
        break;
      case COMILLAS:
        jj_consume_token(COMILLAS);
        break;
      case COMENTARIO:
        jj_consume_token(COMENTARIO);
        break;
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      case NAMEERROR:
        jj_consume_token(NAMEERROR);
        break;
      case SYNTAXERROR:
        jj_consume_token(SYNTAXERROR);
        break;
      case ZERODIVISIONERROR:
        jj_consume_token(ZERODIVISIONERROR);
        break;
      case TYPEERROR:
        jj_consume_token(TYPEERROR);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void programa() throws ParseException {
    jj_consume_token(START);
    label_2:
    while (true) {
      principal();
      if (jj_2_1(20)) {
        ;
      } else {
        break label_2;
      }
    }
    jj_consume_token(END);
    jj_consume_token(0);
  }

  final public void principal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMENTARIO:
      comentario();
      break;
    default:
      jj_la1[2] = jj_gen;
      if (jj_2_2(2)) {
        calculadora();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PRINT:
          imprimir();
          break;
        default:
          jj_la1[3] = jj_gen;
          if (jj_2_3(3)) {
            leer();
          } else if (jj_2_4(10)) {
            declararvar();
          } else if (jj_2_5(3)) {
            operaciones();
          } else if (jj_2_6(3)) {
            asignacionaumentada();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case IF:
              conif();
              break;
            case ELIF:
              conelif();
              break;
            case ELSE:
              conelse();
              break;
            case WHILE:
              ciwhile();
              break;
            default:
              jj_la1[4] = jj_gen;
              if (jj_2_7(4)) {
                contador();
              } else {
                switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
                case FOR:
                  cifor();
                  break;
                case DEF:
                  fdef();
                  break;
                case TRY:
                  intentar();
                  break;
                case DEL:
                  borrar();
                  break;
                case RAISE:
                  fraise();
                  break;
                case NAMEERROR:
                case SYNTAXERROR:
                case ZERODIVISIONERROR:
                case TYPEERROR:
                  errores();
                  break;
                case RETURN:
                  retorno();
                  break;
                case YIELD:
                  fyield();
                  break;
                case LAMBDA:
                  flambda();
                  break;
                default:
                  jj_la1[5] = jj_gen;
                  if (jj_2_8(3)) {
                    fnone();
                  } else {
                    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
                    case NONLOCAL:
                      locales();
                      break;
                    case GLOBAL:
                      globales();
                      break;
                    case ASSERT:
                      fassert();
                      break;
                    case CONTINUE:
                    case FINALLY:
                      finalorcontinue();
                      break;
                    case PASS:
                      fpass();
                      break;
                    case BREAK:
                      romper();
                      break;
                    default:
                      jj_la1[6] = jj_gen;
                      jj_consume_token(-1);
                      throw new ParseException();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  final public void comentario() throws ParseException {
    jj_consume_token(COMENTARIO);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(COMENTARIO);
  }

  final public void calculadora() throws ParseException {
    jj_consume_token(DIGITOS);
    operadorcalculadora();
    jj_consume_token(DIGITOS);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SUMA:
      case RESTA:
      case MULTI:
      case POTENCIA:
      case DIVISION:
      case MODULO:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      operadorcalculadora();
      jj_consume_token(DIGITOS);
    }
    jj_consume_token(PUNTOCOMA);
  }

  final public void operadorcalculadora() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUMA:
      jj_consume_token(SUMA);
      break;
    case RESTA:
      jj_consume_token(RESTA);
      break;
    case MULTI:
      jj_consume_token(MULTI);
      break;
    case DIVISION:
      jj_consume_token(DIVISION);
      break;
    case POTENCIA:
      jj_consume_token(POTENCIA);
      break;
    case MODULO:
      jj_consume_token(MODULO);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void imprimir() throws ParseException {
    jj_consume_token(PRINT);
    jj_consume_token(PARENI);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR2:
      jj_consume_token(IDENTIFICADOR2);
      break;
    case COMILLAS:
      jj_consume_token(COMILLAS);
      opcimprimir();
      jj_consume_token(COMILLAS);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMA);
        opcimprimir2();
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PAREND);
    jj_consume_token(PUNTOCOMA);
  }

  final public void opcimprimir() throws ParseException {
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void opcimprimir2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
      jj_consume_token(COMILLAS);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DIGITOS:
        case IDENTIFICADOR2:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_7;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFICADOR2:
          jj_consume_token(IDENTIFICADOR2);
          break;
        case DIGITOS:
          jj_consume_token(DIGITOS);
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(COMILLAS);
      break;
    default:
      jj_la1[19] = jj_gen;
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DIGITOS:
        case IDENTIFICADOR2:
          ;
          break;
        default:
          jj_la1[17] = jj_gen;
          break label_8;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFICADOR2:
          jj_consume_token(IDENTIFICADOR2);
          break;
        case DIGITOS:
          jj_consume_token(DIGITOS);
          break;
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  final public void leer() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(IGUAL);
    jj_consume_token(INPUT);
    jj_consume_token(PARENI);
    jj_consume_token(COMILLAS);
    opcleer();
    jj_consume_token(COMILLAS);
    jj_consume_token(PAREND);
    jj_consume_token(PUNTOCOMA);
  }

  final public void opcleer() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITOS:
    case IDENTIFICADOR2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
  }

  final public void declararvar() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(IGUAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
    case DIGITOS:
    case IDENTIFICADOR2:
      tipodato();
      break;
    case PARENI:
      tuplas();
      break;
    case CORCHI:
      listas();
      break;
    case LLAVEI:
      diccionario();
      break;
    case FALSE:
    case TRUE:
      bool();
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTOCOMA);
  }

  final public void tuplas() throws ParseException {
    jj_consume_token(PARENI);
    tipodato();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_9;
      }
      jj_consume_token(COMA);
      tipodato();
    }
    jj_consume_token(PAREND);
  }

  final public void listas() throws ParseException {
    jj_consume_token(CORCHI);
    tipodato();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_10;
      }
      jj_consume_token(COMA);
      tipodato();
    }
    jj_consume_token(CORCHD);
  }

  final public void diccionario() throws ParseException {
    jj_consume_token(LLAVEI);
    jj_consume_token(COMILLAS);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(COMILLAS);
    jj_consume_token(DOSPUNTOS);
    tipodato();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_11;
      }
      jj_consume_token(COMA);
      jj_consume_token(COMILLAS);
      jj_consume_token(IDENTIFICADOR2);
      jj_consume_token(COMILLAS);
      jj_consume_token(DOSPUNTOS);
      tipodato();
    }
    jj_consume_token(LLAVED);
  }

  final public void tipodato() throws ParseException {
    if (jj_2_9(2)) {
      jj_consume_token(IDENTIFICADOR2);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGITOS:
        jj_consume_token(DIGITOS);
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PUNTO:
            ;
            break;
          default:
            jj_la1[26] = jj_gen;
            break label_12;
          }
          jj_consume_token(PUNTO);
          jj_consume_token(DIGITOS);
        }
        break;
      case COMILLAS:
        jj_consume_token(COMILLAS);
        jj_consume_token(IDENTIFICADOR2);
        jj_consume_token(COMILLAS);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void bool() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void operaciones() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(IGUALIGUAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR2:
      jj_consume_token(IDENTIFICADOR2);
      break;
    case DIGITOS:
      jj_consume_token(DIGITOS);
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_13:
    while (true) {
      if (jj_2_10(5)) {
        ;
      } else {
        break label_13;
      }
      operadorcalculadora();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(PUNTOCOMA);
  }

  final public void asignacionaumentada() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
    operasinacionaumen();
    opcasignacionaumentada();
    jj_consume_token(PUNTOCOMA);
  }

  final public void operasinacionaumen() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MASIGUAL:
      jj_consume_token(MASIGUAL);
      break;
    case MENOSIGUAL:
      jj_consume_token(MENOSIGUAL);
      break;
    case DIVIGUAL:
      jj_consume_token(DIVIGUAL);
      break;
    case MULTIGUAL:
      jj_consume_token(MULTIGUAL);
      break;
    case DDIGUAL:
      jj_consume_token(DDIGUAL);
      break;
    case RESIGUAL:
      jj_consume_token(RESIGUAL);
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void opcasignacionaumentada() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
  }

  final public void conif() throws ParseException {
    jj_consume_token(IF);
    expresionsimple();
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    label_14:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_14;
      }
    }
    jj_consume_token(LLAVED);
  }

  final public void conelif() throws ParseException {
    jj_consume_token(ELIF);
    expresionsimple();
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    label_15:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_15;
      }
    }
    jj_consume_token(LLAVED);
  }

  final public void conelse() throws ParseException {
    jj_consume_token(ELSE);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    imprimir();
    jj_consume_token(LLAVED);
  }

  final public void ciwhile() throws ParseException {
    jj_consume_token(WHILE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case TRUE:
      bool();
      break;
    case COMILLAS:
    case DIGITOS:
    case IDENTIFICADOR2:
      expresionsimple();
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    label_16:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_16;
      }
    }
    jj_consume_token(LLAVED);
  }

  final public void expresionsimple() throws ParseException {
    tipodato();
    opercomparar();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
    case DIGITOS:
    case IDENTIFICADOR2:
      tipodato();
      break;
    case FALSE:
    case TRUE:
      bool();
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[37] = jj_gen;
        break label_17;
      }
      expresioncompuesta();
    }
  }

  final public void expresioncompuesta() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
      jj_consume_token(AND);
      break;
    case OR:
      jj_consume_token(OR);
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    tipodato();
    opercomparar();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
    case DIGITOS:
    case IDENTIFICADOR2:
      tipodato();
      break;
    case FALSE:
    case TRUE:
      bool();
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void opercomparar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOTNEG:
      jj_consume_token(NOTNEG);
      break;
    case IGUALIGUAL:
      jj_consume_token(IGUALIGUAL);
      break;
    case MAYORQUE:
      jj_consume_token(MAYORQUE);
      break;
    case MENORQUE:
      jj_consume_token(MENORQUE);
      break;
    case IGUAL:
      jj_consume_token(IGUAL);
      break;
    case MAYORIGUAL:
      jj_consume_token(MAYORIGUAL);
      break;
    case MENORIGUAL:
      jj_consume_token(MENORIGUAL);
      break;
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void cifor() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(IN);
    opcfor();
    jj_consume_token(LLAVEI);
    label_18:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[41] = jj_gen;
        break label_18;
      }
    }
    jj_consume_token(LLAVED);
  }

  final public void opcfor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
      jj_consume_token(COMILLAS);
      jj_consume_token(IDENTIFICADOR2);
      jj_consume_token(COMILLAS);
      break;
    case RANGE:
      jj_consume_token(RANGE);
      jj_consume_token(PARENI);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGITOS:
        jj_consume_token(DIGITOS);
        break;
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        break;
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_19:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          ;
          break;
        default:
          jj_la1[43] = jj_gen;
          break label_19;
        }
        jj_consume_token(COMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFICADOR2:
          jj_consume_token(IDENTIFICADOR2);
          break;
        case DIGITOS:
          jj_consume_token(DIGITOS);
          break;
        default:
          jj_la1[44] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(PAREND);
      break;
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void contador() throws ParseException {
    jj_consume_token(IDENTIFICADOR2);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MASIGUAL:
      jj_consume_token(MASIGUAL);
      break;
    case MENOSIGUAL:
      jj_consume_token(MENOSIGUAL);
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(DIGITOS);
    jj_consume_token(PUNTOCOMA);
  }

  final public void fdef() throws ParseException {
    jj_consume_token(DEF);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(PARENI);
    jj_consume_token(IDENTIFICADOR2);
    label_20:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMA:
        ;
        break;
      default:
        jj_la1[47] = jj_gen;
        break label_20;
      }
      jj_consume_token(COMA);
      jj_consume_token(IDENTIFICADOR2);
    }
    jj_consume_token(PAREND);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    label_21:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[48] = jj_gen;
        break label_21;
      }
    }
    jj_consume_token(LLAVED);
  }

  final public void intentar() throws ParseException {
    jj_consume_token(TRY);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    label_22:
    while (true) {
      principal();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NONE:
      case ASSERT:
      case BREAK:
      case CONTINUE:
      case DEF:
      case DEL:
      case ELIF:
      case ELSE:
      case FINALLY:
      case FOR:
      case GLOBAL:
      case IF:
      case LAMBDA:
      case NONLOCAL:
      case PASS:
      case RAISE:
      case RETURN:
      case TRY:
      case WHILE:
      case YIELD:
      case PRINT:
      case NAMEERROR:
      case SYNTAXERROR:
      case ZERODIVISIONERROR:
      case TYPEERROR:
      case COMENTARIO:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[49] = jj_gen;
        break label_22;
      }
    }
    jj_consume_token(LLAVED);
    romper();
    jj_consume_token(EXCEPT);
    errores();
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(LLAVEI);
    imprimir();
    jj_consume_token(LLAVED);
  }

  final public void borrar() throws ParseException {
    jj_consume_token(DEL);
    jj_consume_token(PARENI);
    jj_consume_token(IDENTIFICADOR2);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMILLAS:
    case DIGITOS:
    case IDENTIFICADOR2:
      tipodato();
      break;
    case PARENI:
      tuplas();
      break;
    case CORCHI:
      listas();
      break;
    case LLAVEI:
      diccionario();
      break;
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PAREND);
    jj_consume_token(PUNTOCOMA);
  }

  final public void fraise() throws ParseException {
    jj_consume_token(RAISE);
    errores();
    jj_consume_token(PARENI);
    jj_consume_token(COMILLAS);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(COMILLAS);
    jj_consume_token(PAREND);
    jj_consume_token(PUNTOCOMA);
  }

  final public void errores() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAMEERROR:
      jj_consume_token(NAMEERROR);
      break;
    case SYNTAXERROR:
      jj_consume_token(SYNTAXERROR);
      break;
    case ZERODIVISIONERROR:
      jj_consume_token(ZERODIVISIONERROR);
      break;
    case TYPEERROR:
      jj_consume_token(TYPEERROR);
      break;
    default:
      jj_la1[51] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void retorno() throws ParseException {
    jj_consume_token(RETURN);
    label_23:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE:
      case TRUE:
      case PRINT:
      case PARENI:
      case CORCHI:
      case LLAVEI:
      case COMILLAS:
      case DIGITOS:
      case IDENTIFICADOR2:
        ;
        break;
      default:
        jj_la1[52] = jj_gen;
        break label_23;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRINT:
        imprimir();
        break;
      case COMILLAS:
      case DIGITOS:
      case IDENTIFICADOR2:
        tipodato();
        jj_consume_token(PUNTOCOMA);
        break;
      case PARENI:
        tuplas();
        jj_consume_token(PUNTOCOMA);
        break;
      case CORCHI:
        listas();
        jj_consume_token(PUNTOCOMA);
        break;
      case LLAVEI:
        diccionario();
        jj_consume_token(PUNTOCOMA);
        break;
      case FALSE:
      case TRUE:
        bool();
        jj_consume_token(PUNTOCOMA);
        break;
      default:
        jj_la1[53] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//SE USA DENTRO DE CICLOS, CEDE VALORES PERO NO SALE DEL CICLO , SE USA PARA CREAR GENERADORES
  final public void fyield() throws ParseException {
    jj_consume_token(YIELD);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR2:
      jj_consume_token(IDENTIFICADOR2);
      break;
    case DIGITOS:
      jj_consume_token(DIGITOS);
      break;
    default:
      jj_la1[54] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTOCOMA);
  }

  final public void flambda() throws ParseException {
    jj_consume_token(LAMBDA);
    jj_consume_token(IDENTIFICADOR2);
    operadorcalculadora();
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(PUNTOCOMA);
  }

  final public void fnone() throws ParseException {
    if (jj_2_11(2)) {
      jj_consume_token(NONE);
      jj_consume_token(IGUALIGUAL);
      jj_consume_token(IDENTIFICADOR2);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR2:
        jj_consume_token(IDENTIFICADOR2);
        jj_consume_token(IGUAL);
        jj_consume_token(NONE);
        break;
      case NONE:
        jj_consume_token(NONE);
        jj_consume_token(IGUALIGUAL);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TRUE:
          jj_consume_token(TRUE);
          break;
        case FALSE:
          jj_consume_token(FALSE);
          break;
        default:
          jj_la1[55] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

// SE OCUPAN DENTRO DE FUNCIONES
  final public void locales() throws ParseException {
    jj_consume_token(NONLOCAL);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(PUNTOCOMA);
  }

  final public void globales() throws ParseException {
    jj_consume_token(GLOBAL);
    jj_consume_token(IDENTIFICADOR2);
    jj_consume_token(PUNTOCOMA);
  }

//estÃ¡ instrucciÃ³n recibe una condiciÃ³n a verificar y, opcionalmente, un mensaje de error que devolverÃ¡ en caso que la condiciÃ³n no se cumpla.
  final public void fassert() throws ParseException {
    jj_consume_token(ASSERT);
    jj_consume_token(IDENTIFICADOR2);
    opercomparar();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITOS:
      jj_consume_token(DIGITOS);
      break;
    case FALSE:
    case TRUE:
      bool();
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    imprimir();
  }

  final public void finalorcontinue() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINALLY:
      jj_consume_token(FINALLY);
      jj_consume_token(DOSPUNTOS);
      imprimir();
      break;
    case CONTINUE:
      jj_consume_token(CONTINUE);
      imprimir();
      break;
    default:
      jj_la1[58] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void fpass() throws ParseException {
    jj_consume_token(PASS);
    jj_consume_token(PUNTOCOMA);
  }

  final public void romper() throws ParseException {
    jj_consume_token(BREAK);
    jj_consume_token(PUNTOCOMA);
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_3R_101() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(PASS)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_111() {
    if (jj_scan_token(CONTINUE)) return true;
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_80() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_110()) {
    jj_scanpos = xsp;
    if (jj_3R_111()) return true;
    }
    return false;
  }

  private boolean jj_3R_110() {
    if (jj_scan_token(FINALLY)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_127() {
    if (jj_3R_84()) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_scan_token(ASSERT)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_3R_108()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(98)) {
    jj_scanpos = xsp;
    if (jj_3R_109()) return true;
    }
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_106() {
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(GLOBAL)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_105() {
    if (jj_3R_85()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_scan_token(NONLOCAL)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(NONE)) return true;
    if (jj_scan_token(IGUALIGUAL)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(2)) {
    jj_scanpos = xsp;
    if (jj_scan_token(1)) return true;
    }
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(IGUAL)) return true;
    if (jj_scan_token(NONE)) return true;
    return false;
  }

  private boolean jj_3R_126() {
    if (jj_3R_83()) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_104() {
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(NONE)) return true;
    if (jj_scan_token(IGUALIGUAL)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(LAMBDA)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_103() {
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_107() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_125()) {
    jj_scanpos = xsp;
    if (jj_3R_126()) {
    jj_scanpos = xsp;
    if (jj_3R_127()) {
    jj_scanpos = xsp;
    if (jj_3R_128()) {
    jj_scanpos = xsp;
    if (jj_3R_129()) {
    jj_scanpos = xsp;
    if (jj_3R_130()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_125() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_102() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_scan_token(YIELD)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_100() {
    if (jj_scan_token(COMA)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_107()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_73() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(92)) {
    jj_scanpos = xsp;
    if (jj_scan_token(93)) {
    jj_scanpos = xsp;
    if (jj_scan_token(94)) {
    jj_scanpos = xsp;
    if (jj_scan_token(95)) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_135() {
    if (jj_scan_token(COMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(RAISE)) return true;
    if (jj_3R_73()) return true;
    if (jj_scan_token(PARENI)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(PAREND)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_139() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_scan_token(DEL)) return true;
    if (jj_scan_token(PARENI)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_103()) {
    jj_scanpos = xsp;
    if (jj_3R_104()) {
    jj_scanpos = xsp;
    if (jj_3R_105()) {
    jj_scanpos = xsp;
    if (jj_3R_106()) return true;
    }
    }
    }
    if (jj_scan_token(PAREND)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_scan_token(TRY)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    Token xsp;
    if (jj_3R_102()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_102()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    if (jj_3R_82()) return true;
    if (jj_scan_token(EXCEPT)) return true;
    if (jj_3R_73()) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    if (jj_3R_63()) return true;
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_138() {
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_97() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_121() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(DEF)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(PARENI)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_100()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PAREND)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    if (jj_3R_101()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_101()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(72)) return true;
    }
    if (jj_scan_token(DIGITOS)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_120() {
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_124() {
    if (jj_scan_token(RANGE)) return true;
    if (jj_scan_token(PARENI)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(98)) {
    jj_scanpos = xsp;
    if (jj_scan_token(99)) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_135()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PAREND)) return true;
    return false;
  }

  private boolean jj_3R_98() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_123()) {
    jj_scanpos = xsp;
    if (jj_3R_124()) return true;
    }
    return false;
  }

  private boolean jj_3R_123() {
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_98()) return true;
    if (jj_scan_token(LLAVEI)) return true;
    Token xsp;
    if (jj_3R_99()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_99()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_108() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_134() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(4)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) return true;
    }
    if (jj_3R_83()) return true;
    if (jj_3R_108()) return true;
    xsp = jj_scanpos;
    if (jj_3R_138()) {
    jj_scanpos = xsp;
    if (jj_3R_139()) return true;
    }
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_3R_92()) return true;
    return false;
  }

  private boolean jj_3R_122() {
    if (jj_3R_134()) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_3R_83()) return true;
    if (jj_3R_108()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_120()) {
    jj_scanpos = xsp;
    if (jj_3R_121()) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_122()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_95() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    if (jj_3R_63()) return true;
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_32()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(ELIF)) return true;
    if (jj_3R_92()) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    Token xsp;
    if (jj_3R_94()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(WHILE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) return true;
    }
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    if (jj_3R_97()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_97()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_92()) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_scan_token(LLAVEI)) return true;
    Token xsp;
    if (jj_3R_93()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_93()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_116() {
    if (jj_scan_token(COMA)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_3R_59()) return true;
    if (jj_scan_token(99)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(2)) {
    jj_scanpos = xsp;
    if (jj_scan_token(1)) return true;
    }
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(IGUALIGUAL)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_10()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_85()) return true;
    return false;
  }

  private boolean jj_3R_141() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_137() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_141()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_131() {
    if (jj_scan_token(PUNTO)) return true;
    if (jj_scan_token(DIGITOS)) return true;
    return false;
  }

  private boolean jj_3R_118() {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_133()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3R_113() {
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    return false;
  }

  private boolean jj_3R_115() {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_112() {
    if (jj_scan_token(DIGITOS)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_131()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_83() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3R_112()) {
    jj_scanpos = xsp;
    if (jj_3R_113()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    return false;
  }

  private boolean jj_3R_114() {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(LLAVEI)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(DOSPUNTOS)) return true;
    if (jj_3R_83()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_116()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVED)) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(CORCHI)) return true;
    if (jj_3R_83()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_115()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(CORCHD)) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_scan_token(PARENI)) return true;
    if (jj_3R_83()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_114()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PAREND)) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_3R_117()) return true;
    if (jj_scan_token(COMILLAS)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_118()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(IGUAL)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    }
    }
    }
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_140() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_119() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_91() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_119()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_3R_32()) return true;
    if (jj_scan_token(DIGITOS)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(IDENTIFICADOR2)) return true;
    if (jj_scan_token(IGUAL)) return true;
    if (jj_scan_token(INPUT)) return true;
    if (jj_scan_token(PARENI)) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_3R_91()) return true;
    if (jj_scan_token(COMILLAS)) return true;
    if (jj_scan_token(PAREND)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_136() {
    if (jj_scan_token(COMILLAS)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_140()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(COMILLAS)) return true;
    return false;
  }

  private boolean jj_3R_133() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_136()) {
    jj_scanpos = xsp;
    if (jj_3R_137()) return true;
    }
    return false;
  }

  private boolean jj_3R_132() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_117() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_132()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_scan_token(PARENI)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_3R_90()) return true;
    }
    if (jj_scan_token(PAREND)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_88() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(98)) return true;
    }
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(DIGITOS)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(DIGITOS)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_89()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(COMENTARIO)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_88()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(COMENTARIO)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_81()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_78()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_76()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_75()) return true;
    return false;
  }

  private boolean jj_3R_130() {
    if (jj_3R_87()) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_74()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_109() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_129() {
    if (jj_3R_86()) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(BREAK)) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  private boolean jj_3R_128() {
    if (jj_3R_85()) return true;
    if (jj_scan_token(PUNTOCOMA)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public PythonTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[59];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xfffffffe,0xfffffffe,0x0,0x0,0x80083000,0x70810c00,0x90482c0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x6,0x0,0x0,0x0,0x0,0x0,0x6,0x0,0x0,0x0,0xf98dbec8,0xf98dbec8,0x6,0xf98dbec8,0x6,0x4000010,0x4000010,0x6,0x0,0xf98dbec8,0x0,0x0,0x0,0x0,0x0,0x0,0xf98dbec8,0xf98dbec8,0x0,0x0,0x6,0x6,0x0,0x6,0x8,0x6,0x8200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xffffffff,0xffffffff,0x0,0x10,0x0,0x2,0x0,0x0,0x0,0x5f00,0x5f00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x48000000,0x0,0x0,0x0,0x20000000,0x0,0x0,0x0,0x0,0x0,0x12,0x12,0x0,0x12,0x0,0x0,0x0,0x0,0x7e00000,0x12,0x0,0x0,0x0,0x4,0x0,0x0,0x12,0x12,0x48000000,0x0,0x48000010,0x48000010,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0xffffffff,0xffffffff,0x0,0x0,0x0,0xf0000000,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x4,0x4,0x4,0x0,0x0,0x0,0x0,0x0,0x1f80,0xf0000000,0xf0000000,0x0,0xf0000000,0x0,0x0,0x0,0x0,0x20,0xf0000000,0x0,0x4,0x0,0x0,0x180,0x4,0xf0000000,0xf0000000,0x1,0xf0000000,0x1,0x1,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0xf,0xf,0x2,0x0,0x0,0x0,0x0,0xc,0xc,0x0,0x0,0x0,0x9,0xc,0xc,0xc,0xc,0xc,0xc,0x1,0xc,0xc,0xd,0x0,0x0,0x0,0x0,0x5,0x0,0xc,0xc,0x0,0xe,0xe,0xd,0xe,0xd,0x0,0x0,0xd,0x0,0xe,0xc,0x0,0xc,0x1,0x0,0x0,0xe,0xe,0xd,0x0,0xd,0xd,0xc,0x0,0x8,0x4,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[11];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Python(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Python(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new PythonTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Python(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new PythonTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Python(PythonTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(PythonTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[106];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 59; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 106; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 11; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
